### ISSUE TITLE
Création image depuis flux geoportail

### ISSUE THREAD

**Issue by Chrispnv** [Viglino/Geoportail-KISS#1]
Bonjour,

J'ai beaucoup appris avec le site geopole sur l'api geoportail depuis que je travaille sur des applis carto web. Je me permets de vous écrire pour un obstacle que je rencontre.

J'utilise l'api Geoportail avec leaflet avec de nombreuses applis carto web. cela marche très bien. Maintenant je veux aller plus loin, c'est pourvoir mettre dans un PDF une extraction - partie de la carte IGN courante - depuis des coordonnées passée dans l'url et aussi passé un geojson pour qu'un point apparaisse aussi.
J'ai trouvé comment faire avec un flux mapbox : voir le lien suivant : https://jsfiddle.net/fexymjy3/11/ et je l'ai mis dans jsfiddle https://jsfiddle.net/sig_pnv/6w5nqj22/ donc avec un flux mapbox voici ce qu'il faut faire : 
FLUX INITIAL dans un objet map
https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpandmbXliNDBjZWd2M2x6bDk3c2ZtOTkifQ._QA7i5Mpkd_m30IGElHziw
FLUX pour créer une image
var imageUrl = "https://api.tiles.mapbox.com/v4/mapbox.streets/geojson("+ encodedData+")/"+ center.lng+","+center.lat+","+mymap._zoom+"/400x400.png?access_token=pk.eyJ1IjoiZGF2aWRsb3R0IiwiYSI6IjdlNmU1ZWUyMDE5MDcwMDQ5YTNiN2IyZTIzYjZkNTg5In0.sDTxz1C0DTl3UH7AguCBXg";

J'aimerais bien faire cela avec un flux geoportail 
var imageUrl = "https://gpp3-wxs.ign.fr/maclé/geoportail/wmts?LAYER=GEOGRAPHICALGRIDSYSTEMS.MAPS&EXCEPTIONS=text/xml&FORMAT=image/jpeg&SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetTile&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}";
J'ai essayé quelques solution sans succès. J'ai l'impression que vous matisez bien la carto sur la web. Avez vous une idée pour créer une image depuis un flux geoportail en apportant des coordonnées de position et dans la meilleur des cas passer un geojson pour afficher un vecteur.

Je vous remercie d'avance.

@Chrispnv

**Comment by Chrispnv** [comment]
Je maitrise mal github donc je rajoute ce commentaire avec votre pseudo @Viglino pour vous alerter de mon issue.
Merci.
@Chrispnv

**Comment by Viglino** [comment]
Bonjour,

L'exemple que vous citez utilise la [Static API de Mapbox](https://www.mapbox.com/api-documentation/#static-classic) qui permet de charger une image statique. Ce n'est donc pas possible avec d'autres type de flux que ceux de [MapBox](https://www.mapbox.com/help/create-a-static-map/).
Cela ne marchera pas pour un flux Geoportail.
Vous pouvez regarder du côté des plugin Leaflet (http://leafletjs.com/plugins.html#printexport) et du [plugin leaflet image](https://github.com/mapbox/leaflet-image) mais je ne suis pas sûr qu'il permette l'intégration de geojson.

Si vous avez vraiment besoins de réaliser des export PDF de cartes, il faudra vous orienter vers d'autres librairie que Leaflet. [OL3](http://openlayers.org/) permet ce genre de chose et donne de très bon résultats : http://openlayers.org/en/latest/examples/export-pdf.html.
Vous pouvez même ajouter d'autres éléments que des couches à la carte (titre, échelle, attribution > voir http://viglino.github.io/ol3-ext/examples/map.canvas.control.html).

@+
